name: mutsplice
channels:
  - conda-forge
  - bioconda
dependencies:
    - python=3.10.12
    - cudatoolkit=11.2.2
    - cudnn=8.1.0
    - meme=5.5.3
    - pip=23.2.1
    - pip:
       - tensorflow==2.11.0
       - spliceai==1.3.1
       - pandas==2.0.3
       - numpy==1.23.5
       - seaborn
       - pyranges
       - biopython==1.77
       - dna_features_viewer
       - loguru
       - tqdm
       - pandarallel
       - cyvcf2
       - mygene
